### ISSUE TITLE
Missing Positional Argument Issue

### ISSUE THREAD

**Issue by iasarthak** [thismlguy/code-genie#2]
When I ran the default example as shown in readme, I got an error - 
![image](https://user-images.githubusercontent.com/58847609/234208247-b92a452a-d6fd-4e69-94a5-e96c76d56e6a.png)

After running the same thing with `columns = None`,
another error popped up -
![image](https://user-images.githubusercontent.com/58847609/234209200-a7398549-7e1f-43ff-ba06-606f911a478e.png)

**Comment by thismlguy** [comment]
@iasarthak - the `columns` argument is required as of now. but that should be optional, i can fix it in the next release.
the other error is because the right way to call the method would be `genie(df=df)`. this should however again not be a required property, will fix in the next release as well.

**Comment by thismlguy** [comment]
@iasarthak - resolved in #3

**Comment by iasarthak** [comment]
Thanks a lot @thismlguy! That was quick!
